version: '3'

services:
  php:
    environment:
      - XDEBUG_SESSION=docker-server
    build:
      ./php
    volumes:
      - ./:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "81:80"
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pswd
    container_name: mysql_container
    ports:
      - "3306:3306"

#   restart: always
