version: '3'

services:
  php:
    environment:
      - XDEBUG_SESSION=docker-server
    build:
      ./php
    volumes:
      - ./:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "81:80"


  db:
   container_name: db
   image: mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: testdb
    MYSQL_USER: user
    MYSQL_PASSWORD: pswd
   ports:
     - "9906:3306"
